name: my_check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: install dependencies
        run: |
          pip install poetry flake8 pytest
          pip3 install flask
          make install
      - name: Run linter
        run: make lint